server:
  port: 8080

spring:
  application:
    name: fuel_management
  datasource:
    url: jdbc:mysql://localhost:3306/fuelman
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: giang412345
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: debug
  file:
    name: logs/app.log



